{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.deployment.name }}-secret
  namespace: {{ .Values.deployment.namespace }}
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: {{ .Values.externalSecrets.storeRef.name }}
    kind: {{ .Values.externalSecrets.storeRef.kind }}
  target:
    name: {{ .Values.deployment.name }}-secret
    creationPolicy: Owner
  data:
    - secretKey: RDS_USERNAME
      remoteRef:
        key: {{ .Values.externalSecrets.rdsSecretName }}
        property: username
    - secretKey: RDS_PASSWORD
      remoteRef:
        key: {{ .Values.externalSecrets.rdsSecretName }}
        property: password
    - secretKey: RDS_HOST
      remoteRef:
        key: {{ .Values.externalSecrets.rdsSecretName }}
        property: host
    - secretKey: RDS_PORT
      remoteRef:
        key: {{ .Values.externalSecrets.rdsSecretName }}
        property: port
{{- end }}
